-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- PROFILES TABLE (Extends Auth Users)
create table profiles (
  id uuid references auth.users not null primary key,
  email text,
  role text default 'user', -- 'user', 'admin', 'vip'
  full_name text,
  avatar_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for Profiles
alter table profiles enable row level security;
create policy "Public profiles are viewable by everyone." on profiles for select using (true);
create policy "Users can insert their own profile." on profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile." on profiles for update using (auth.uid() = id);

-- NEWS TABLE
create table news (
  id bigint generated by default as identity primary key,
  title text not null,
  source text,
  status text default 'Draft', -- 'Draft', 'Published'
  date date default current_date,
  image text,
  body text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- PREDICTIONS TABLE
create table predictions (
  id bigint generated by default as identity primary key,
  match text not null,
  outcome text not null,
  odds text,
  confidence text default 'Medium',
  status text default 'Draft',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- MATCH INSIGHTS TABLE (For BookView)
create table match_insights (
  id bigint generated by default as identity primary key,
  title text not null,
  source text,
  time_ago text, -- or use created_at to calculate
  excerpt text,
  image text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- STORAGE BUCKET 'cms-images'
-- You must create a storage bucket named 'cms-images' in the Supabase Dashboard
-- Policy: Give public read access, authenticated insert access.

-- RLS for Content (News, Predictions, Insights)
-- Public Read
alter table news enable row level security;
create policy "News is viewable by everyone" on news for select using (true);

alter table predictions enable row level security;
create policy "Predictions are viewable by everyone" on predictions for select using (true);

alter table match_insights enable row level security;
create policy "Insights are viewable by everyone" on match_insights for select using (true);

-- Admin Write (Logic handled in app via role check, or strictly here if using custom claims)
-- For simplicity in this demo, we allow authenticated users to write (assuming admin accounts are secured)
-- Ideally: create policy "Admins can update" on news for all using ( exists (select 1 from profiles where id = auth.uid() and role = 'admin') );

create policy "Auth users can insert news" on news for insert with check (auth.role() = 'authenticated');
create policy "Auth users can update news" on news for update using (auth.role() = 'authenticated');
create policy "Auth users can delete news" on news for delete using (auth.role() = 'authenticated');

create policy "Auth users can insert predictions" on predictions for insert with check (auth.role() = 'authenticated');
create policy "Auth users can update predictions" on predictions for update using (auth.role() = 'authenticated');
create policy "Auth users can delete predictions" on predictions for delete using (auth.role() = 'authenticated');

create policy "Auth users can insert insights" on match_insights for insert with check (auth.role() = 'authenticated');
create policy "Auth users can update insights" on match_insights for update using (auth.role() = 'authenticated');
create policy "Auth users can delete insights" on match_insights for delete using (auth.role() = 'authenticated');
